POST http://localhost:5000/register/Admin
Content-Type: application/json

{
    "emailR":"sundar@gmail.com",
    "passwordR":"sundar",
    "designation":"lecture",
    "department":"cse"
}

###
POST http://localhost:5000/login/Admin
Content-Type: application/json

{
    "email":"sundar@gmail.com",
    "password":"sundar"
}


###
GET http://localhost:5000/details/Admin?id=Admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmUwZDQ5MjAxNzRmMDJmMWZhZTZlMCIsImlhdCI6MTY1MTM3OTc2OCwiZXhwIjoxNjUzOTcxNzY4fQ.T5KDaVmll_he4xCWKzy1l2CfqDszVZS8oWZ0FQQrzCg

