POST http://localhost:5000/register/Admin
Content-Type: application/json

{
    "name":"hari",
    "email":"haran1763@gmail.com",
    "password":"haran1763"
}

###
POST http://localhost:3000/login/Admin
Content-Type: application/json

{
    "username":"hari",
    "email":"haran1763@gmail.com",
    "password":"haran1763"
}


###
GET http://localhost:3000/Admin/Admin?id=Admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzQ5OGZiYmU2M2IwZTYyZmYzZGU0YSIsImlhdCI6MTY0NzY5ODIwMCwiZXhwIjoxNjUwMjkwMjAwfQ.JAV7zoWTOiKDMIc8DyL09SFw_FY-HQQSp61D8SGBfC4

